package com.waimaibang.model;

import lombok.Data;

import java.util.Date;
import java.util.List;

/**
 * @author zhouguanya
 */
@Data
public class Consumer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * destinationList： 一个消费者对应N个destination
     */
    private List<Destination> destinationList;
}