package com.waimaibang.model;

import lombok.Data;

import java.util.Date;
import java.util.List;

/**
 * @author zhouguanya
 */
@Data
public class Destination {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destination.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destination.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destination.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destination.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destination.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destination.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * 生产者列表：一个destination对应多个Producer
     */
    private List<Producer> producerList;

    /**
     * 消费者列表：一个destination对应多个Consumer
     */
    private List<Consumer> consumerList;
}