package com.waimaibang.model;

import lombok.Data;

import java.util.Date;

/**
 * @author zhouguanya
 */
@Data
public class Producer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producer.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producer.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producer.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producer.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producer.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * destination 一个生产者对应一个destination
     */
    private Destination destination;
}