package com.waimaibang.dao;

import com.waimaibang.model.Producer;
import com.waimaibang.model.ProducerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProducerDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producer
     *
     * @mbg.generated
     */
    long countByExample(ProducerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producer
     *
     * @mbg.generated
     */
    int deleteByExample(ProducerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producer
     *
     * @mbg.generated
     */
    int insert(Producer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producer
     *
     * @mbg.generated
     */
    int insertSelective(Producer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producer
     *
     * @mbg.generated
     */
    List<Producer> selectByExample(ProducerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producer
     *
     * @mbg.generated
     */
    Producer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Producer record, @Param("example") ProducerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Producer record, @Param("example") ProducerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Producer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Producer record);
}